config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'welcome#index'
  get '/jobs', to: 'jobs#index'
  post 'apply', to: 'jobs#apply'
  resources :applicants, only: [:show, :new, :create]
  resources :employers, only: [:show, :new, :create] do
    resources :jobs
  end
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :jobs, through: :applications

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :user_id, presence: true
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :applicant
  belongs_to :job

  validates :applicant_id, presence: true
  validates :job_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  belongs_to :user
  has_many :jobs
  has_many :applications, through: :jobs

  validates :name, presence: true
  validates :user_id, presence: true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :employer
  has_many :applications
  has_many :applicants, through: :applications

  validates :employer_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w(applicant employer).freeze

  has_one :applicant, dependent: :destroy
  has_one :employer, dependent: :destroy

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates_inclusion_of :role,
    in: ROLES
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action { validate_role('applicant', 'employer') }

  def show
    applicant = Applicant.find_by(user_id: current_user.id)
    @applications = applicant.applications
  end

  def new
    @user_id = current_user.id
  end

  def create
    Applicant.create(applicant_params)
    redirect_to applicant_path(current_user.id)
  end

  private

  def applicant_params
    params.require(:applicant).permit(:user_id, :first_name, :last_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def validate_role(role, redirect_resource)
    return if current_user.role == role

    if current_user.role == redirect_resource
      flash[:notice] = "You do not have access to the #{role} portal."
      redirect_to send("#{redirect_resource}_path".to_sym, current_user.id)
    else
      redirect_to root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end

  def after_sign_in_path_for(resource)
    if resource.role == 'applicant'
      applicant_path(resource.id)
    elsif resource.role == 'employer'
      employer_path(resource.id)
    else
      root_path
    end
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action { validate_role('employer', 'applicant') }

  def show
    @employer = Employer.find_by(user_id: current_user.id)
    @jobs = @employer.jobs
    @applications = @employer.applications
  end

  def new
    @user_id = current_user.id
  end

  def create
    Employer.create(employer_params)
    redirect_to employer_path(employer_params[:user_id])
  end

  private

  def employer_params
    params.require(:employer).permit(:user_id, :name)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @jobs = Job.all
    @employer = current_user.employer
    @applicant = current_user.applicant
  end

  def apply
    job = Job.find(params[:job_id])
    Application.create(applicant_id: current_user.applicant.id, job_id: job.id)
    flash[:success] = "You applied to the #{job.title} position!"
    redirect_to applicant_path(current_user.id)
  end

  def new
    @employer = Employer.find(params[:employer_id])
    @job = Job.new(employer_id: @employer.id)
  end

  def create
    Job.create(
      title: job_params[:title],
      description: job_params[:description],
      employer_id: current_user.employer.id
    )

    redirect_to employer_path(current_user.id)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :employer_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    if resource.role == 'applicant'
      new_applicant_path
    elsif resource.role == 'employer'
      new_employer_path
    else
      root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/applicants/new.html.erb
<h2>Create Applicant User</h2>

<%= form_for :applicant, url: { action: "create" }  do |f| %>
  <%= f.hidden_field(:user_id, value: @user_id) %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/applicants/show.html.erb
<h2>Applications</h2>
<% if @applications.empty? %>
  You haven't submitted any applications. Check out the <%= link_to 'jobs', jobs_path %> page to find your next role!
<% else %>
  Check out the <%= link_to 'jobs', jobs_path %> page to apply to more roles!
  <table class='table'>
    <thead>
        <tr>
          <th scope='col'>Date Applied</th>
          <th scope='col'>Company</th>
          <th scope='col'>Title</th>
          <th scope='col'>Description</th>
        </tr>
      </thead>
    <% @applications.each do |application| %>
      <tbody>
        <tr>
          <td><%= application.created_at %></td>
          <td><%= application.job.employer.name %></td>
          <td><%= application.job.title %></td>
          <td><%= application.job.description %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% end %>

app/views/employers/new.html.erb
<h2>Create Employer User</h2>

<%= form_for :employer, url: { action: "create" }  do |f| %>
  <%= f.hidden_field(:user_id, value: @user_id) %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/employers/show.html.erb
<div>
  <% if @applications.empty? %>
    You have no pending applications.
  <% else %>
  <h2>Applicants</h2>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>Date Applied</th>
          <th scope='col'>Job Title</th>
          <th scope='col'>Applicant Name</th>
        </tr>
      </thead>
      <% @applications.each do |application| %>
        <tbody>
          <tr>
            <td><%= application.created_at %></td>
            <td><%= application.job.title %></td>
            <td><%= application.applicant.first_name %> <%= application.applicant.last_name %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>
</div>

<div>
  <h2>Jobs</h2>
  <% if @jobs.empty? %>
    <%= link_to 'Create', new_employer_job_path(@employer) %> more jobs!
  <% else %>
    <div>
      <%= link_to 'Create Job', new_employer_job_path(@employer) %>
    </div>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>Created At</th>
          <th scope='col'>Title</th>
          <th scope='col'>Description</th>
        </tr>
      </thead>
      <% @jobs.each do |job| %>
        <tbody>
          <tr>
            <td><%= job.created_at %></td>
            <td><%= job.title %></td>
            <td><%= job.description %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>
  
</div>

app/views/jobs/index.html.erb
<div>
  <% if @jobs.empty? %>
    No jobs have been posted.
  <% else %>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>Created At</th>
          <th scope='col'>Company</th>
          <th scope='col'>Title</th>
          <th scope='col'>Description</th>
          <th scope='col'></th>
        </tr>
      </thead>
      <% @jobs.each do |job| %>
        <tbody>
          <tr>
            <td><%= job.created_at %></td>
            <td><%= job.employer.name %></td>
            <td><%= job.title %></td>
            <td><%= job.description %></td>
            <td><%= 
              link_to_unless @employer || (@applicant && Application.find_by(applicant_id: @applicant.id, job_id: job.id)), 'Apply', apply_path(job_id: job.id), method: :post %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>  
</div>

app/views/jobs/new.html.erb
<h2>Create Job</h2>

<%= form_for [@employer, @job], url: { action: 'create' } do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fountain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>

      <%= bootstrap_flash %>

      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>  
        </li>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
Welcome!